[package]
name = "kingletp"
version = "0.1.0"
authors = ["Pyfisch <pyfisch@gmail.com>"]

[dependencies]
hyper = "*"
httparse = "*"
multimap = { git="https://github.com/pyfisch/multimap.git", rev="779f3f85" }
unicase = "*"
url = "*"
time = "*"
